### PR TITLE
Add Laravel 10 support

### LINKED ISSUE #97: Add Laravel 10 support
Add support for Laravel 10.

### PR DESCRIPTION
**Pull request by adamjgriffith**
Add Laravel 10 support.

Fixes #97.

@nonoesp @mpociot

### CODE REVIEW

**Comment by adamjgriffith** [comment]
@mpociot I think if this package is no longer maintained it should be mentioned in the README.md and deprecated / archived as currently it is not clear and people may use it without realising.

**Comment by nonoesp** [comment]
Hey, @adamjgriffith!

Thanks a lot for the pull request, I appreciate your effort.

I've been doing minor maintenance for compatibility with newer Lavarel versions. But haven't had the time to review this for Laravel 10.

I'm okay with adding a note on the README saying this package has low maintenance.

I can test this and merge if everything is fine.

Kindly,
Nono

**Comment by nonoesp** [comment]
@adamjgriffith I've tested your changes on a fresh Laravel 10 app.

```sh
composer create-project laravel/laravel app
```

I installed your package with the following `composer.json` to test locally.

```json
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/adamjgriffith/versionable"
        }
    ],    
    "require": {
        "php": "^8.1",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.0",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "mpociot/versionable": "dev-feature/laravel-10"
    },
```

```
composer update
```

Ran the migrations.

```bash
php artisan vendor:publish --provider="Mpociot\Versionable\Providers\ServiceProvider" --tag="migrations"
```

Created a simple versionable class.

```php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \Mpociot\Versionable\VersionableTrait;

class Item extends Model
{
    use VersionableTrait;
	use SoftDeletes;

	/**
	 * @var string
	 */
	protected $table;

	/**
	 * @var boolean
	 */
	protected $softDelete = true;
	
	/**
	 * @var array
	 */	
	protected $dontVersionFields = [
		'meta',
	];

	public function __construct() {
	    parent::__construct();
	    $this->table = 'items';
	}

}
```

Migrations.

```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('items', function (Blueprint $table) {
            $table->id();
            $table->string('title')->nullable();
            $table->string('description')->nullable();
            $table->string('meta')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('items');
    }
};
```

Then tested items can be versioned.

```php
    $item = new App\Models\Item();
    $item->title = 'test title';
    $item->description = 'test description';
    $item->meta = 'test meta';
    $item->save();

    $item->description = 'a new description';
    $item->save();
```

Existing tests pass.

```
› vendor/bin/phpunit
PHPUnit 10.0.15 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.3
Configuration: /Users/nono/Desktop/tmp/laravel-10/phpunit.xml

..                                                                  2 / 2 (100%)

Time: 00:00.125, Memory: 24.00 MB

OK (2 tests, 2 assertions)
```

**Comment by nonoesp** [comment]
Thanks again for the work, @adamjgriffith. 👌🏻🙂

**Pull request merged**
