### PR TITLE
Added support for laravel 7

### PR DESCRIPTION
**Pull request by stojankukrika**

### CODE REVIEW

**Comment by skipworkgh** [comment]
@mpociot Can we have this PR merged?

**Comment by nonoesp** [comment]
I also added [this line](https://github.com/nonoesp/versionable/commit/1289d508eccde5a6a7c90c54bec4d027d3daca30) to this patch for the service provider to automatically include this package when running `php artisan migrate`.

---

For those of you who (like me) got here trying to figure out how to use @stojankukrika's `patch-1` branch (or mine), just add this to the repositories block of your `composer.json` and set the version requirement to `dev-patch-1` (see below).

To use [stojankukrika/versionable@patch-1](https://github.com/stojankukrika/versionable/tree/patch-1)

```php
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/stojankukrika/versionable"
        }
    ],
```

To use [nonoesp/versionable@patch-1](https://github.com/nonoesp/versionable/tree/patch-1)

```php
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/nonoesp/versionable"
        }
    ],
```

And then in the require block.

```
    "require": {
        // ...
        "mpociot/versionable": "dev-patch-1"
    },
```

**Comment by stojankukrika** [comment]
I just want to notify you that I just published a package based on this package. So any update is welcome here https://packagist.org/packages/stojankukrika/versionable

**Comment by nonoesp** [comment]
Great to hear @stojankukrika. Thanks for doing this! 🥳

Will make a pull request to your repository.

**Comment by mpociot** [comment]
Hey @stojankukrika 
Sorry for not replying.

I am personally no longer using this package, so maintaining it has become quite hard for me.
Would you like to step up and become a maintainer of this package, instead of the fork? :)

**Comment by nonoesp** [comment]
↑ That sounds like a better approach to me.

**Comment by mpociot** [comment]
Or if anyone else wants to help with the maintenance, that's also good :)

**Comment by nonoesp** [comment]
I'm using this package a lot in https://github.com/nonoesp/laravel-folio.

Wouldn't mind joining as maintainer. =)

**Comment by mpociot** [comment]
Awesome, thank you. I just added you to the repo

**Pull request closed without merging**
