### PR TITLE
different versions table

### PR DESCRIPTION
**Pull request by Cyrille37**
Hi,
I did a feature that permits to use different versions table, model by model.

I've updated the README that u can see how it works, and UnitTest to check that it works :-)

Cheers
Cyrille.

### CODE REVIEW

**Comment by Cyrille37** [comment]
Argh! Travis-ci could not success ...

image

**Comment by Cyrille37** [comment]
Argh! My syntax is not compatible with Php 5.5 ... Grrrh ...

**Comment by Cyrille37** [comment]
It's not my syntax that make travis-ci failed :-)

It's package dependencies that are not available with Php 5.5

image

**Comment by Cyrille37** [comment]
Hi @mpociot 
Do you/we need compatibility with Php 5.5 ? Notice that the problem is with dev tool (Mockery)

image

**Comment by jhayiwg** [comment]
This looks promising I hope this will merge as soon as possible, I wanted to use this package but I wanted my models to include versions.

**Comment by Cyrille37** [comment]
Thanks !!

**Pull request merged**
