### PR TITLE
use connection of model

### PR DESCRIPTION
**Pull request by spresnac**

### CODE REVIEW

**Comment by mpociot** [comment]
If I understand your issue right, you want to use the connection of the model that you are versioning, correct?

**Comment by spresnac** [comment]
@mpociot Yes, exactly

**Comment by mpociot** [comment]
Okay - got it.
But I think this PR would introduce some breaking changes.

For example:

Your default connection is DB1 and you have another connection DB2

The version table gets migrated to the default connection and only exists on DB1.

When I now try to save a model that lives on DB2 it will not work with this PR in place, as it will use the wrong database connection.

I think a better approach would be to make the version model configurable. This way you can create your own version model, change it in the config file and use the connection that you want in this specific version model.

**Comment by spresnac** [comment]
@mpociot Yes, this would be best way to do it ;)

**Comment by mpociot** [comment]
The version model is now configurable: https://github.com/mpociot/versionable/commit/9abd756eca24969eff85ff9f08cbce3afa991e0b#diff-8c6999c6977539530459d4be9a3a5150R10

I tagged a new version (3.1.0) with this fix

**Pull request closed without merging**
